/** @type {import('tailwindcss').Config} */
export default {
    content: [
      "./src/**/*.{astro,html,js,ts,jsx,tsx,md,mdx}",
    ],
    // Style-guide "Primary Scale" swatches build class names dynamically
    // (`bg-primary-${step}`) which Tailwind's static scan can't see.
    safelist: [
      "bg-primary-50", "bg-primary-100", "bg-primary-200", "bg-primary-300",
      "bg-primary-400", "bg-primary-500", "bg-primary-600", "bg-primary-700",
      "bg-primary-800", "bg-primary-900",
    ],
    theme: {
      extend: {
        fontFamily: {
          display: ['Space Grotesk', 'ui-sans-serif', 'system-ui', 'sans-serif'],
          sans: ['Manrope', 'ui-sans-serif', 'system-ui', 'sans-serif'],
          heading: ['Space Grotesk', 'ui-sans-serif', 'system-ui', 'sans-serif'],
          body: ['Manrope', 'ui-sans-serif', 'system-ui', 'sans-serif'],
          label: ['Space Grotesk', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        },
        colors: {
          primary: {
            50: 'oklch(var(--primary-50) / <alpha-value>)',
            100: 'oklch(var(--primary-100) / <alpha-value>)',
            200: 'oklch(var(--primary-200) / <alpha-value>)',
            300: 'oklch(var(--primary-300) / <alpha-value>)',
            400: 'oklch(var(--primary-400) / <alpha-value>)',
            500: 'oklch(var(--primary-500) / <alpha-value>)',
            600: 'oklch(var(--primary-600) / <alpha-value>)',
            700: 'oklch(var(--primary-700) / <alpha-value>)',
            800: 'oklch(var(--primary-800) / <alpha-value>)',
            900: 'oklch(var(--primary-900) / <alpha-value>)',
            950: 'oklch(var(--primary-950) / <alpha-value>)',
          },
          accent: {
            50: 'oklch(var(--accent-50) / <alpha-value>)',
            100: 'oklch(var(--accent-100) / <alpha-value>)',
            200: 'oklch(var(--accent-200) / <alpha-value>)',
            300: 'oklch(var(--accent-300) / <alpha-value>)',
            400: 'oklch(var(--accent-400) / <alpha-value>)',
            500: 'oklch(var(--accent-500) / <alpha-value>)',
            600: 'oklch(var(--accent-600) / <alpha-value>)',
            700: 'oklch(var(--accent-700) / <alpha-value>)',
            800: 'oklch(var(--accent-800) / <alpha-value>)',
            900: 'oklch(var(--accent-900) / <alpha-value>)',
            950: 'oklch(var(--accent-950) / <alpha-value>)',
          },
          secondary: {
            50: 'oklch(var(--secondary-50) / <alpha-value>)',
            100: 'oklch(var(--secondary-100) / <alpha-value>)',
            200: 'oklch(var(--secondary-200) / <alpha-value>)',
            300: 'oklch(var(--secondary-300) / <alpha-value>)',
            400: 'oklch(var(--secondary-400) / <alpha-value>)',
            500: 'oklch(var(--secondary-500) / <alpha-value>)',
            600: 'oklch(var(--secondary-600) / <alpha-value>)',
            700: 'oklch(var(--secondary-700) / <alpha-value>)',
            800: 'oklch(var(--secondary-800) / <alpha-value>)',
            900: 'oklch(var(--secondary-900) / <alpha-value>)',
            950: 'oklch(var(--secondary-950) / <alpha-value>)',
          },
          background: {
            50: 'oklch(var(--background-50) / <alpha-value>)',
            100: 'oklch(var(--background-100) / <alpha-value>)',
            200: 'oklch(var(--background-200) / <alpha-value>)',
            300: 'oklch(var(--background-300) / <alpha-value>)',
            400: 'oklch(var(--background-400) / <alpha-value>)',
            500: 'oklch(var(--background-500) / <alpha-value>)',
            600: 'oklch(var(--background-600) / <alpha-value>)',
            700: 'oklch(var(--background-700) / <alpha-value>)',
            800: 'oklch(var(--background-800) / <alpha-value>)',
            900: 'oklch(var(--background-900) / <alpha-value>)',
            950: 'oklch(var(--background-950) / <alpha-value>)',
          },
          foreground: {
            50: 'oklch(var(--foreground-50) / <alpha-value>)',
            100: 'oklch(var(--foreground-100) / <alpha-value>)',
            200: 'oklch(var(--foreground-200) / <alpha-value>)',
            300: 'oklch(var(--foreground-300) / <alpha-value>)',
            400: 'oklch(var(--foreground-400) / <alpha-value>)',
            500: 'oklch(var(--foreground-500) / <alpha-value>)',
            600: 'oklch(var(--foreground-600) / <alpha-value>)',
            700: 'oklch(var(--foreground-700) / <alpha-value>)',
            800: 'oklch(var(--foreground-800) / <alpha-value>)',
            900: 'oklch(var(--foreground-900) / <alpha-value>)',
            950: 'oklch(var(--foreground-950) / <alpha-value>)',
          },
        },
        borderRadius: {
          none: '0px',
          sm: '0px',
          DEFAULT: '0px',
          md: '0px',
          lg: '0px',
          xl: '0px',
          '2xl': '0px',
          '3xl': '0px',
          full: '0px',
        },
        boxShadow: {
          none: 'none',
          sm: 'none',
          DEFAULT: 'none',
          md: 'none',
          lg: 'none',
          xl: 'none',
          '2xl': 'none',
          inner: 'none',
        },
        keyframes: {
          'pulse-dot': {
            '0%, 100%': { opacity: '1', transform: 'scale(1)' },
            '50%': { opacity: '0.4', transform: 'scale(1.4)' },
          },
          'float-up': {
            '0%': { transform: 'translateY(8px)', opacity: '0' },
            '100%': { transform: 'translateY(0)', opacity: '1' },
          },
          'reveal-up': {
            '0%': { transform: 'translateY(28px)', opacity: '0' },
            '100%': { transform: 'translateY(0)', opacity: '1' },
          },
          'reveal-left': {
            '0%': { transform: 'translateX(-24px)', opacity: '0' },
            '100%': { transform: 'translateX(0)', opacity: '1' },
          },
          'reveal-right': {
            '0%': { transform: 'translateX(24px)', opacity: '0' },
            '100%': { transform: 'translateX(0)', opacity: '1' },
          },
          marquee: {
            '0%': { transform: 'translateX(0)' },
            '100%': { transform: 'translateX(-50%)' },
          },
        },
        animation: {
          'pulse-dot': 'pulse-dot 1.8s ease-in-out infinite',
          'float-up': 'float-up 0.6s ease-out both',
          'reveal-up': 'reveal-up 0.8s cubic-bezier(0.22, 1, 0.36, 1) both',
          'reveal-left': 'reveal-left 0.8s cubic-bezier(0.22, 1, 0.36, 1) both',
          'reveal-right': 'reveal-right 0.8s cubic-bezier(0.22, 1, 0.36, 1) both',
          'marquee': 'marquee 60s linear infinite',
        },
      },
    },
    plugins: [],
  }