// Subset Remix Icon to only the glyphs used in src, and emit a minimal CSS.
// Re-run whenever icon usage changes:  node scripts/subset-icons.mjs
import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join } from "node:path";
import subsetFont from "subset-font";

const ROOT = process.cwd();
const SRC = join(ROOT, "src");
const PKG = join(ROOT, "node_modules", "remixicon", "fonts");
const OUT_CSS = join(SRC, "styles", "remixicon.css");
const OUT_FONT = join(SRC, "styles", "remixicon.woff2");

// 1. collect used ri- classes from source (exclude the icon css/styles dir)
function walk(dir) {
  const out = [];
  for (const n of readdirSync(dir)) {
    const p = join(dir, n);
    if (statSync(p).isDirectory()) { if (n !== "styles") out.push(...walk(p)); }
    else if (/\.(tsx?|ts)$/.test(n)) out.push(p);
  }
  return out;
}
const used = new Set();
for (const f of walk(SRC)) {
  for (const m of readFileSync(f, "utf8").matchAll(/ri-[a-z0-9]+(?:-[a-z0-9]+)*/g)) used.add(m[0]);
}

// 2. map class -> codepoint from the package css
const pkgCss = readFileSync(join(PKG, "remixicon.css"), "utf8");
const cp = {};
for (const m of pkgCss.matchAll(/\.(ri-[a-z0-9-]+):before\s*\{\s*content:\s*"\\([0-9a-fA-F]+)"/g)) {
  cp[m[1]] = m[2];
}

const kept = [], missing = [];
for (const c of [...used].sort()) (cp[c] ? kept : missing).push(c);
if (missing.length) console.warn("  ! no codepoint (skipped):", missing.join(", "));

// 3. subset the woff2 to the used codepoints
const text = kept.map((c) => String.fromCodePoint(parseInt(cp[c], 16))).join("");
const srcFont = readFileSync(join(PKG, "remixicon.woff2"));
const subset = await subsetFont(srcFont, text, { targetFormat: "woff2" });
writeFileSync(OUT_FONT, subset);

// 4. emit minimal css: @font-face + base rule + only-used glyph rules
const rules = kept.map((c) => `.${c}:before { content: "\\${cp[c]}"; }`).join("\n");
const css = `/* Remix Icon — SUBSET (${kept.length} glyphs used on this site).
   Generated by scripts/subset-icons.mjs — do not hand-edit; re-run the script. */
@font-face {
  font-family: "remixicon";
  src: url("./remixicon.woff2") format("woff2");
  font-display: swap;
}
[class^="ri-"], [class*=" ri-"] {
  font-family: "remixicon" !important;
  font-style: normal;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
${rules}
`;
writeFileSync(OUT_CSS, css);

console.log(`Subset ${kept.length} glyphs -> ${(subset.length / 1024).toFixed(1)}KB woff2 (was ${(srcFont.length / 1024).toFixed(1)}KB)`);
